(key-chord-define-global "jj" nil)
(key-chord-define-global "a0" 'avy-goto-word-1)
(key-chord-define-global "a9" 'avy-goto-char)
(key-chord-define-global "fd" 'paredit-forward)
(key-chord-define-global "ds" 'paredit-backward)
(key-chord-define-global "xf" 'forward-char)
(key-chord-define-global "xb" 'ido-switch-buffer)
(key-chord-define-global "xd" 'backward-char)
(key-chord-define-global "cz" 'other-window)
(key-chord-define-global "xc" 'easy-kill)
(key-chord-define-global "xv" 'yank)
(key-chord-define-global "xs" 'save-buffer-always)
(key-chord-define-global "xj" 'lispy-forward)
(key-chord-define-global "xk" 'lispy-backward)

(require 'cider)
;; (key-chord-define cider-mode-map "cf" 'cider-eval-defun-at-point)
(key-chord-define cider-mode-map "vv" 'cider-eval-sexp-at-point)
